# Generated by Django 4.2 on 2023-06-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="description",
            field=models.TextField(
                max_length=500, null=True, verbose_name="Ürün Açıklaması:"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(null=True, upload_to="product/"),
        ),
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.IntegerField(null=True, verbose_name="Ürün Fiyatı: "),
        ),
    ]
