# Generated by Django 4.2 on 2023-07-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_products_description_products_image_products_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kategori Adı")),
            ],
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                null=True, upload_to="product/", verbose_name="Ürün Resmi: "
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.category",
            ),
        ),
    ]
