# Generated by Django 4.2 on 2023-07-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_serino_alter_products_category_products_seri_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="AltKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="products",
            name="seri_no",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.serino",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="alt_kategori",
            field=models.ManyToManyField(blank=True, to="products.altkategori"),
        ),
    ]
