# Generated by Django 4.2 on 2023-07-19 19:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0005_altkategori_alter_products_seri_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=ckeditor.fields.RichTextField(
                max_length=500, null=True, verbose_name="Ürün Açıklaması:"
            ),
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adet", models.IntegerField()),
                ("total", models.IntegerField()),
                ("odendiMi", models.BooleanField(default=False)),
                (
                    "ekleyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
