# Generated by Django 4.2 on 2023-07-31 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0006_alter_products_description_basket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="odendiMi",
            field=models.BooleanField(default=False, verbose_name="Tutar Ödendi mi ?"),
        ),
        migrations.CreateModel(
            name="Odeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField()),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                ("urunler", models.ManyToManyField(to="products.products")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
