# Generated by Django 4.2 on 2023-07-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_basket_odendimi_odeme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odeme",
            name="urunler",
            field=models.ManyToManyField(to="products.basket"),
        ),
    ]
