# Generated by Django 4.2 on 2023-07-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_odeme_urunler"),
    ]

    operations = [
        migrations.AddField(
            model_name="odeme",
            name="odendiMi",
            field=models.BooleanField(default=False),
        ),
    ]
